-- Respaldo de Customers generado el 2026-08-27 antes de recrear la tabla
SET IDENTITY_INSERT [Customers] ON;
INSERT INTO [Customers] (Id,CompanyName,ContactName,ContactTitle,Address,City,Region,PostalCode,Country,Phone,Fax,CreatedAt,CreatedBy,LastUpdatedAt,LastUpdatedBy) VALUES (2, N'assa', N'fd', N'RUBEN', N'RUBEN', N'RUBEN', N'RUBEN', N'RUBEN', N'RUBEN', N'RUBEN', N'RUBEN', '2026-08-27T07:42:45.512', NULL, '2026-08-27T08:41:52.076', N'System');
INSERT INTO [Customers] (Id,CompanyName,ContactName,ContactTitle,Address,City,Region,PostalCode,Country,Phone,Fax,CreatedAt,CreatedBy,LastUpdatedAt,LastUpdatedBy) VALUES (3, N'FSDG', N'string', N'string', N'string', N'string', N'string', N'string', N'string', N'string', N'string', '2026-08-26T11:35:16.727', N'System', '2026-08-27T08:40:55.956', N'System');
INSERT INTO [Customers] (Id,CompanyName,ContactName,ContactTitle,Address,City,Region,PostalCode,Country,Phone,Fax,CreatedAt,CreatedBy,LastUpdatedAt,LastUpdatedBy) VALUES (6, N'DSADS', N'sdffd', N'string', N'string', N'string', N'string', N'string', N'string', N'string', N'string', '2026-08-27T07:49:44.860', N'System', '2026-08-27T07:49:45.307', N'System');
INSERT INTO [Customers] (Id,CompanyName,ContactName,ContactTitle,Address,City,Region,PostalCode,Country,Phone,Fax,CreatedAt,CreatedBy,LastUpdatedAt,LastUpdatedBy) VALUES (7, N'FGGF', N'strgdfgffing', N'dgffgffg', N'string', N'string', N'string', N'string', N'string', N'string', N'string', '2026-08-27T08:01:58.158', N'System', '2026-08-27T08:01:58.712', N'System');
INSERT INTO [Customers] (Id,CompanyName,ContactName,ContactTitle,Address,City,Region,PostalCode,Country,Phone,Fax,CreatedAt,CreatedBy,LastUpdatedAt,LastUpdatedBy) VALUES (8, N'gfFSDAFD', N'string', N'fgdgf', N'string', N'string', N'string', N'dffg', N'string', N'string', N'string', '2026-08-27T08:11:24.381', N'System', '2026-08-27T08:11:26.189', N'System');
INSERT INTO [Customers] (Id,CompanyName,ContactName,ContactTitle,Address,City,Region,PostalCode,Country,Phone,Fax,CreatedAt,CreatedBy,LastUpdatedAt,LastUpdatedBy) VALUES (9, N'gfgdf', N'string', N'gfdf', N'string', N'string', N'string', N'string', N'string', N'string', N'string', '2026-08-27T15:32:24.091', N'System', '2026-08-27T15:32:24.091', N'System');
INSERT INTO [Customers] (Id,CompanyName,ContactName,ContactTitle,Address,City,Region,PostalCode,Country,Phone,Fax,CreatedAt,CreatedBy,LastUpdatedAt,LastUpdatedBy) VALUES (10, N'dsds', N'string', N'string', N'string', N'string', N'string', N'string', N'string', N'string', N'string', '2026-08-27T15:53:16.952', N'System', '2026-08-27T15:53:16.952', N'System');
SET IDENTITY_INSERT [Customers] OFF;
